### ISSUE TITLE
ganeti-mond in 2.15.2 appears to leak file descriptors

### ISSUE THREAD

**Issue by Ganeti-Issues-Migrator** [ganeti/ganeti#1241]
Originally reported of Google Code with ID 1188.

```
What software version are you running? Please provide the output of "gnt-
cluster --version", "gnt-cluster version", and "hspace --version".

On a cluster running:

- gentoo host - kernel 4.4.6                                                
- ganeti 2.15.2                                                             
- drbd 8.4.5 (api:1/proto:86-101)                                           
- qemu 2.7.0        

A user noticed ganeti-mond dying and restarting every ~45 mins.

/var/log/ganeti/monitoring-daemon.log contains entries like:

2016-09-13 13:45:02,526598000000 CEST: ganeti-mond pid=13626/ThreadId 3     
NOTICE ganeti-mond daemon startup                                           
ganeti-mond: file descriptor 1024 out of range for select (0--1024).        
Recompile with -threaded to work around this.                               

At first glance, this looks like it could be a file-descriptor leak. mond shouldn't need to have that many files/sockets open simultaneous.

```
Originally added on 2016-09-14 12:45:32 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
I take a look on my nodes in /proc/$(pidof ganeti-mond)/fd
and there is 2 new pipe link that appears every 5s:

l-wx------ 1 root root 64 Sep 14 22:53 820 -> pipe:[13902781]
lr-x------ 1 root root 64 Sep 14 22:53 821 -> pipe:[13902782]

/proc/15720/fd/820: broken symbolic link to pipe:[13902781]
/proc/15720/fd/821: broken symbolic link to pipe:[13902782]


Right after ganeti-mond is launched:

lr-x------ 1 root root 64 Sep 14 22:57 0 -> /dev/null
l-wx------ 1 root root 64 Sep 14 22:57 1 -> /var/log/ganeti/monitoring-daemon.log
l-wx------ 1 root root 64 Sep 14 22:57 10 -> pipe:[13926595]
lr-x------ 1 root root 64 Sep 14 22:57 11 -> pipe:[13926596]
l-wx------ 1 root root 64 Sep 14 22:57 2 -> /var/log/ganeti/monitoring-daemon.log
lr-x------ 1 root root 64 Sep 14 22:57 3 -> /var/lib/ganeti/ssconf_master_node
lrwx------ 1 root root 64 Sep 14 22:57 4 -> socket:[13906864]
lrwx------ 1 root root 64 Sep 14 22:57 6 -> /run/ganeti/ganeti-mond.pid
l-wx------ 1 root root 64 Sep 14 22:57 7 -> /var/log/ganeti/monitoring-daemon-access.log
l-wx------ 1 root root 64 Sep 14 22:57 8 -> /var/log/ganeti/monitoring-daemon-error.log
lrwx------ 1 root root 64 Sep 14 22:57 9 -> socket:[13906866]


/proc/5602/fd/0:  symbolic link to /dev/null
/proc/5602/fd/1:  symbolic link to /var/log/ganeti/monitoring-daemon.log
/proc/5602/fd/10: broken symbolic link to pipe:[13926595]
/proc/5602/fd/11: broken symbolic link to pipe:[13926596]
/proc/5602/fd/2:  symbolic link to /var/log/ganeti/monitoring-daemon.log
/proc/5602/fd/3:  symbolic link to /var/lib/ganeti/ssconf_master_node
/proc/5602/fd/4:  broken symbolic link to socket:[13906864]
/proc/5602/fd/6:  symbolic link to /run/ganeti/ganeti-mond.pid
/proc/5602/fd/7:  symbolic link to /var/log/ganeti/monitoring-daemon-access.log
/proc/5602/fd/8:  symbolic link to /var/log/ganeti/monitoring-daemon-error.log
/proc/5602/fd/9:  broken symbolic link to socket:[13906866]

So the process reach 1024 broken symbolic link to pipe in 1024/2/60*5 = 42.66 mn
And since the watcher check and restart the process every 5mn by cron, the process is restarted every 45mn as observed.
```
Originally added on 2016-09-14 21:03:35 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
# gnt-cluster version 
Software version: 2.15.2
Internode protocol: 2150000
Configuration format: 2150000
OS api version: 20
Export interface: 0
VCS version: (ganeti) version v2.14.2-177-g003cd9a

```
Originally added on 2016-09-14 21:05:07 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
I tried to reproduce this on my 2.17 setup using Xen and DRBD, but couldn't. I'll continue looking at it, but out of interest could you tell me which collectors are enabled on your system? You can do this by running the following on the master
wget -qO - http://127.0.0.1:1815/1/list/collectors | /etc/ganeti/share/fmtjson

For me, the only collectors that were enabled were drbd, inst-status-xen and diagnose.

```
Originally added on 2016-09-17 11:46:04 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
# wget -qO - http://127.0.0.1:1815/1/list/collectors | /etc/ganeti/share/fmtjson
[
  [
    "cpu-avg-load",
    "default",
    0
  ],
  [
    "xen-cpu-avg-load",
    "default",
    0
  ],
  [
    "diskstats",
    "storage",
    0
  ],
  [
    "drbd",
    "storage",
    1
  ],
  [
    "lv",
    "storage",
    0
  ]

Don't hesitate to ask me if you need that I dig further.

```
Originally added on 2016-09-19 11:54:35 +0000 UTC.

**Comment by Ganeti-Issues-Migrator** [comment]
```
I have stop the file descriptor leak by stopping monitor of xen-cpu-avg-load and inst-status-xen since we don't use xen (xen not installed and ganeti not compiled with xen support).

So now I got:

Data collectors: 
  cpu-avg-load: 
    active: True
    interval: 5.000s
  diskstats: 
    active: True
    interval: 5.000s
  drbd: 
    active: True
    interval: 5.000s
  inst-status-xen: 
    active: False
    interval: 5.000s
  lv: 
    active: True
    interval: 5.000s
  xen-cpu-avg-load: 
    active: False
    interval: 5.000s

Thanks to lead me on the right direction.
```
Originally added on 2016-10-05 17:00:53 +0000 UTC.
