### ISSUE TITLE
name- and ip-checking opt-in maybe incomplete (RAPI)

### ISSUE THREAD

**Issue by saschalucas** [ganeti/ganeti#1841]
While testing `move-instance`, which uses RAPI to create instances on dest-cluster, an error is thrown regarding DNS resolution: _The given name (test.vm) does not resolve: Name or service not known_. Adding test.vm to dest-cluster's /etc/hosts fixes the issue. This happens despite `ip_check: False` and `name_check: False` are set in the CREATE request.

Maybe commit 31e5194a9fa24053defce12d58f8fc5c6fc9c907 is incomplete. RAPI instance creation should be checked.

```
root@master:~# gnt-job info 10
- Job ID: 10
  Status: error
  Received:         2025-04-06 09:48:43.614378
  Processing start: 2025-04-06 09:48:43.999605 (delta 0.385227s)
  Processing end:   2025-04-06 09:48:44.138633 (delta 0.139028s)
  Total processing time: 0.524255 seconds
  Opcodes: 
    - Opcode: OP_INSTANCE_CREATE
      Status: error
      Processing start: 2025-04-06 09:48:43.999605
      Execution start:  N/A
      Processing end:   2025-04-06 09:48:44.138618
      Input fields: 
        OP_ID: OP_INSTANCE_CREATE
        beparams: 
          maxmem: 1024
          minmem: 1024
          vcpus: 1
        comment: None
        commit: False
        compress: none
        conflicts_check: True
        debug_level: 0
        depends: None
        disk_template: plain
        disks: 
          - mode: rw
            name: None
            size: 5120
        dry_run: False
        force_variant: False
        forthcoming: False
        helper_shutdown_timeout: 7200
        helper_startup_timeout: 300
        hvparams: 
        hypervisor: kvm
        iallocator: hail
        identify_defaults: False
        ignore_ipolicy: False
        instance_communication: False
        instance_name: test.vm
        ip_check: False
        mode: remote-import
        name_check: False
        nics: 
          - ip: 10.0.0.61
            link: gnt-br0
            mac: aa:00:00:15:b5:fd
            mode: bridged
            network: 0363d22e-41ca-4c3d-b46a-95fed55f9ed7
            vlan: 
        opportunistic_locking: False
        os_type: instance-guestfish+debian-bookworm
        osparams: 
        priority: 0
        reason: 
          - - gnt:library:rlib2:instances
            - 
            - 1743925723442927872
          - - gnt:opcode:instance_create
            - job=10;index=0
            - 1743925723614378000
        source_handshake: 
          - 0
          - b90d3e23333fa795fadfe46eda6a4bb64814b5dd
          - 1bfe557fb5016bc9
        source_instance_name: test.vm
        source_shutdown_timeout: 120
        source_x509_ca: X-Ganeti-Signature: 3ec0bf5684b2b3a6/4a9f4625282d7ecfe359ae7b549fed035edc3e85

-----BEGIN CERTIFICATE-----
MIIC/TCCAeUCBGfyMdowDQYJKoZIhvcNAQELBQAwQzFBMD8GA1UEAww4bm9kZTAy
LjRlNmE1NTQ5N2MxMzljYjdlNWE5NDc5MDhhNDU2NmRjZDA3NWJjNjcuZ250LnRl
c3QwHhcNMjUwNDA2MDc0ODQyWhcNMjUwNDA3MDc0ODQyWjBDMUEwPwYDVQQDDDhu
b2RlMDIuNGU2YTU1NDk3YzEzOWNiN2U1YTk0NzkwOGE0NTY2ZGNkMDc1YmM2Ny5n
bnQudGVzdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKbT6DQPOUME
MYtdq3g5S/T6wFNz10HbxtSDo9MNuwGadEFYYv5X8Uc+TUrzS4H5cR+rzSrqvvNP
TsBLWdeyfSY2dZDmhkVHE7avIe/f6HHPqTl9S+3KX+BolSEBFPVJsgpehncH6m0J
A3PDUHk4mwHaLZ90fq0FYQJ0E77Sq8cM9jIjno/EWYAkVwnEaFTb3vJeZkjmElNT
pxeOz8yiWYOyuK28BfWyXje2KV+bc6wFj8Apg7m1/Kk7vhJoPLmzX0gluLTs6eGT
EMXJ2rSKc8XvENogg7BlbV50W4Ez36kv3TTwiGdAnnA35WDNWtUvLqZQs7xZyNR5
PjihQxhQDX8CAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAlXznQS0Mszy/t9oe3Hob
MetWxDQIq83XASpnmHClaUp4O0/R6SLVLM8NOCqsVUmRwcKSa9OuBcyEUy2u1O2T
b9sLgY2gMFFRYLMLXUsnY3NvdJUjEUXx+GjWO+rnHEy+dKpgcOD8CNJFPDNw7q+s
HmioTBjqeYdjg1TTABgApAwfLXZzloIb0u19G39yV2dfGhmBUW8LSd+wzHHll79T
yLAy7x02XRblIbtTCFeW+5/J32Crycs9Pvoji9G+x9hjTezwMFB+Rq7K4qZ54RvN
Z5zmbgwdXePrMSZfu3e+v3k4zQVqq6LUX6ffE9rrMJw99ypuAaeLxAFqDN3otpGT
HA==
-----END CERTIFICATE-----

        start: True
        tags: 
        wait_for_sync: False
      Result: 
        - OpPrereqError
        - - The given name (test.vm) does not resolve: Name or service not known
          - resolver_error
      Execution log: 

```
